In [2]:
import pandas as pd

import numpy as np

## Python Basics

### Ranges and Arrays
- For creating a series of numbers
- `np.arange(start_num, end_num, steps)`

In [7]:
lst = [1,2,3,4,5]
# np.arage(0, N, 1)

np.arange(0, 4, 1)

array([0, 1, 2, 3])

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
"""
Try returning:
array([5, 10, 15, 20])
"""

np.arange(5, 25, 5)

array([ 5, 10, 15, 20])

In [12]:
# Descending array

np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

In [13]:
"""
Try returning:
array([10, 7, 4])
"""

np.arange(10, 3, -3)

array([10,  7,  4])

### Conditions
- Operates by boolean
- `if condition == True`:
    - `print('yes')`
- `else`:
    - `print('no')`
 

In [15]:
color = 'red'

if color == 'blue':
    print('yes')
else:
    print('no')

no


In [17]:
color = 'yellow'

if color == 'blue':
    print('yes')
elif color == 'red':
    print('red')
else:
    print('no')

no


In [18]:
"""
Try returning:
if age is between 15 - 17, print middle school student
if age is between 18 - 20, print high school student
if age is over 20, print adult
else, print else
"""

age = 18
if 15 <= age <= 17:
    print("middle school student")
elif 18 <= age <= 20:
    print('high school student')
elif 20 < age:
    print('adult')
else: 
    print('else')

high school student


### For Loops
- For iterating over a series of values and repeating certain calculation
- `for i in range(start_num, end_num, steps)`:
    - `Execute a function`
- by default, `for i in range(0, end_num, 1)`

In [19]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [20]:
for i in range(2, 20, 3):
    print(i)

2
5
8
11
14
17


In [24]:
# Nested for loop
shirt = ['blue', 'purple', 'red']
pants = ['green', 'black', 'white']

for i in shirt:
    for j in pants:
        print(i, j)

green blue
green purple
green red
black blue
black purple
black red
white blue
white purple
white red


In [26]:
"""
Try returning:
1 ~ 9단 구구단
1 X 1
1 X 2
1 X 3
1 X 4
1 X 5
...
9 X 9
"""
for i in range(1, 9):
    for j in range(1, 9):
        print(i, 'X', j)

1 X 1
1 X 2
1 X 3
1 X 4
1 X 5
1 X 6
1 X 7
1 X 8
2 X 1
2 X 2
2 X 3
2 X 4
2 X 5
2 X 6
2 X 7
2 X 8
3 X 1
3 X 2
3 X 3
3 X 4
3 X 5
3 X 6
3 X 7
3 X 8
4 X 1
4 X 2
4 X 3
4 X 4
4 X 5
4 X 6
4 X 7
4 X 8
5 X 1
5 X 2
5 X 3
5 X 4
5 X 5
5 X 6
5 X 7
5 X 8
6 X 1
6 X 2
6 X 3
6 X 4
6 X 5
6 X 6
6 X 7
6 X 8
7 X 1
7 X 2
7 X 3
7 X 4
7 X 5
7 X 6
7 X 7
7 X 8
8 X 1
8 X 2
8 X 3
8 X 4
8 X 5
8 X 6
8 X 7
8 X 8


Adding elements to an empty list
- `lst.append(element)`

In [29]:
numbers = [0, 61, 7, 8, 109]
newnumbers = []
for i in numbers:
    newnum = i + 10
    newnumbers.append(newnum)

print(newnumbers)

[10, 71, 17, 18, 119]


Strings
- `stringvalue += 'string'`

In [33]:
firstname = 'Jinwoo'
lastname = 'moon'
firstname + lastname

'Jinwoomoon'

In [34]:
"""
Try creating a new array by appending string values
Return:
['blue shirt', 'purple shirt', 'red shirt']
"""

shirts = ['blue', 'purple', 'red']
clothes = []

for i in shirts:
    newclothes = i + ' shirt'
    clothes.append(newclothes)
    
print(clothes)

['blue shirt', 'purple shirt', 'red shirt']


`break`: stop iterating and exit out of for loop \
`continue`: loop back to the beginning of the loop

In [36]:
lst = ['hi', 'hello', 'bye']
for i in lst:
    if i == 'hello':
        continue
    print(i)

hi
bye


In [37]:
"""
Try this:
Return pass message if a student's mark is over 60 points
"""
marks = [90, 25, 67, 45, 80]

# student number
number = 0 
for mark in marks: 
    number = number + 1
    if mark < 60:
        continue 
    print("{}번 학생 축하합니다. 합격입니다. ".format(number))

1번 학생 축하합니다. 합격입니다. 
3번 학생 축하합니다. 합격입니다. 
5번 학생 축하합니다. 합격입니다. 


In [38]:
nums = [1,2,3,4]
for i in nums:
    print("{}번 학생 축하합니다. 합격입니다. ".format(i))

1번 학생 축하합니다. 합격입니다. 
2번 학생 축하합니다. 합격입니다. 
3번 학생 축하합니다. 합격입니다. 
4번 학생 축하합니다. 합격입니다. 


### Dictionaries
- Operates under key-value relationship
- `dict = {'Jinwoo': 19, 'Emily': 15}`

In [39]:
a = {'name': 'pey', 'phone': '0119993323', 'birth': '1118'}

In [41]:
# values()
a.values()

dict_values(['pey', '0119993323', '1118'])

In [42]:
# items()
a.keys()

dict_keys(['name', 'phone', 'birth'])

In [43]:
a.items()

dict_items([('name', 'pey'), ('phone', '0119993323'), ('birth', '1118')])

In [46]:
dict = {'Jinwoo': 19, 'Emily': 15}
# Iterating over dictionary
for key, i in dict.items():
    print(key, i)

Jinwoo 19
Emily 15


### While Loop
- For repeating a function until it reaches certain condition
- `while condition:` 
    - `execute a function`

In [48]:
count = 10

while count > 0:
    print(count)
    count = count - 1

10
9
8
7
6
5
4
3
2
1


In [49]:
# watch out for infinite loop!
count = 0
while True:
    print("Infinite loop")
    count += 1
    if count == 1000:
        break
    

Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infinite loop
Infini

In [51]:
# break in while loop
status = True
result = 0

while status:
    result += 1
    if result > 5:
        status = False

print(result)

6


In [ ]:
"""
Try implementing 
If treehit reaches 10, the tree falls
Until it reaches 10, print the number of treehits

"""

treeHit = 0

while treeHit < 10:
    treeHit = ...
    print("나무를 {}d번 찍었습니다.".format(treeHit)
    if ...:
        print("나무 넘어갑니다.")

In [53]:
"""
Try implementing a coffee vending machine
Coffee is 300 won.

If a person pays 300 won, sell coffee
If a person pays less than 300 won, return the money and don't sell coffee
If a person pays more than 300 won, sell coffee and return change
If coffee is sold out, break while loop and stop selling

"""

coffee = 5
while True:
    money = int(input("돈을 넣어 주세요: "))
    if money == 300:
        print("커피를 줍니다.")
        coffee = coffee -1
    elif money > 300:
        print("거스름돈 {}를 주고 커피를 줍니다.".format(money - 300))
        coffee = coffee - 1
    else:
        print("돈을 다시 돌려주고 커피를 주지 않습니다.")
        print("남은 커피의 양은 {}개 입니다.".format(coffee))
    if coffee == 0:
        print("커피가 다 떨어졌습니다. 판매를 중지 합니다.")
        break

KeyboardInterrupt: Interrupted by user